### ISSUE TITLE
CPU Load

### ISSUE THREAD

**Issue by thmang82** [L1nY4n/mqtt_v#1]
Totally like the idea! A lot of MQTT clients are heavy side.
This one is easy to compile, fast startup, ... just RUST :-)

But: there is a bug regarding CPU load!

After startup, about 40%  of one CPU-core is consumed. Not stellar, but quite ok.

But: after a disconnect, and re-connect to a saved connection, a full thread is blocked, over all usage going to 130%.
Each additional disconnect/reconnect, it jumps another 100% :-(

**Comment by L1nY4n** [comment]
@thmang82 thanks for your feedback 
It is a BUG:  when disconnect a client,  message channel ( backend -> ui ) create with should  be closed and dropped but not. I made a low mistake here 😂
Please check out this [fix](https://github.com/L1nY4n/mqtt_v/commit/27a0c9198c3ab94dd738a4b4227cdb8ad1e5de9c) to see if slove the problem or not.
